default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>
  host: <%= ENV['TEMPLATE_DATABASE_HOSTNAME'] || 'localhost' %>
  username: <%= ENV['TEMPLATEAPP_DATABASE_USER'] || 'rails' %>
  password: <%= ENV['TEMPLATEAPP_DATABASE_PASSWORD'] || 'rails' %>

development:
  <<: *default
  database: <%= ENV['TEMPLATEAPP_DATABASE'] || 'player_management_dev' %>
  
test:
  <<: *default
  database: <%= ENV['TEMPLATEAPP_DATABASE'] || 'player_management_test' %>
  
production:
  database: <%= ENV['DATABASE_URL'] %>
  